const ActionTypes = {
    CREATE_USER: "CREATE_USER",
    CREATE_USER_LOADING: "CREATE_USER_LOADING",
    CREATE_USER_ERROR: "CREATE_USER_ERROR",
    LOGIN_USER: "LOGIN_USER",
    LOGIN_USER_LOADING: "LOGIN_USER_LOADING",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
};

export default ActionTypes;